---
title: "PsoReg arsrapport Martin 2016"
author: "martin"
date: "18 januari 2016"
output: word_document
---
```{r databearbetningar1, echo=FALSE}

library(reshape)
#library(xtable)

library(knitr)
library(stringr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(pyramid)
#library(data.table)

#Läser in data med kontakter från PsoReg
Pso_contact <- read.delim(file="H:/Martin/PsoReg/Projekt PsoReg årsrapport 2016/årsrapport 2016 WD/data för PsoReg årsrapport 16/Kontaktnivå 20160118.txt",header=TRUE,sep="\t",encoding="UTF-8", dec=",")

#namnger variablerna ändra datatyper, plockar bort testpatienter och plockar bort kontakter utan kontaktdatum och kontakter efter 2015-12-31
names(Pso_contact)[1:9]<- c("PERSNR","Pnyckel_contact","Pnyckel_root","Fnyckel_contact","PAT_ID","Kön","Aktiv_patient", "Sjukhus","ContactDate")
Pso_contact$Sjukhus <- as.character(Pso_contact$Sjukhus)
Pso_contact <- Pso_contact[!(Pso_contact$Sjukhus=="Test") ,]
Pso_contact$ContactDate <- as.Date(Pso_contact$ContactDate)
Pso_contact <- subset(Pso_contact, is.na(ContactDate)==FALSE)
Pso_contact <- subset(Pso_contact, ContactDate<"2016-01-01")


#Sorterar datat och skapar en variabel som indikerar de unika individerna dupli_PatientID=FALSE=första kontakten per individ
Pso_contact <- Pso_contact[order(Pso_contact$ContactDate,decreasing=FALSE),]
Pso_contact <- Pso_contact[order(Pso_contact$PERSNR,decreasing=FALSE),]
Pso_contact$dupli_PatientID <- duplicated(Pso_contact$PERSNR)

#lite fix
Pso_contact$Contact_year <- 1900 + as.POSIXlt(Pso_contact$ContactDate)$year
Pso_contact$Contact_moth <-1 + as.POSIXlt(Pso_contact$ContactDate)$mon
Pso_contact$Contact_year_moth <- paste(as.character(Pso_contact$Contact_year),as.character(Pso_contact$Contact_moth),sep ="")
Pso_contact$REGDATUM <- as.character(Pso_contact$REGDATUM)
Pso_contact$REGDATUM[Pso_contact$REGDATUM==""] <- "1900-01-01"
Pso_contact$REGDATUM <- as.Date(Pso_contact$REGDATUM)
Pso_contact$Registred_year <- 1900 + as.POSIXlt(Pso_contact$REGDATUM)$year
Pso_contact$Registred_moth <-1 + as.POSIXlt(Pso_contact$REGDATUM)$mon
Pso_contact$Registred_year_moth <- paste(as.character(Pso_contact$Registred_year),as.character(Pso_contact$Registred_moth),sep ="")

Pso_contact$PERSNR <- gsub("[^0-9]", "", Pso_contact$PERSNR) 

Pso_contact$Kön <-ifelse(Pso_contact$Kön==1,"Man" , "Kvinna")
Pso_contact$Ålder <- 2015-as.numeric(substr(Pso_contact$PERSNR,1,4))
Pso_contact$Ålder_kategori <- cut(Pso_contact$Ålder, breaks = c(10,30,45,60,75,120), right = FALSE)

Pso_contact$Ålder_kategori2 <- cut(Pso_contact$Ålder, breaks = c(0,14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89, 94),labels=FALSE)
Pso_contact$Ålder_kategori2 <-as.factor(Pso_contact$Ålder_kategori2)



#Skapar dataset med den senaste kontakten per individ
Pso_individ<-subset(Pso_contact,dupli_PatientID==FALSE)
  ###############



```


```{r databearbetningar 2, echo=FALSE}
#####Läser in fil med systembehandlingar#####

#Läser in data med PsoReg data för att skapa dataset med behandlingar
Pso_behandling <- read.csv("H:/Martin/PsoReg/Projekt PsoReg årsrapport 2016/årsrapport 2016 WD/data för PsoReg årsrapport 16/Systembehandlingar 20160118.txt",header=TRUE,sep="\t",encoding="UTF-8")
names(Pso_behandling) <- c("PERSNR", "Pnyckel_systemictreat", "Fnyckel_systemictreat","Sjukhus", "InsertDate", "RemoveDate", "DrugName","biologisk","Aktiv_patient")
Pso_behandling <- Pso_behandling[!(Pso_behandling$Sjukhus=="Test") ,]
#Pso_behandling <- Pso_behandling[as.numeric(substr(Pso_behandling$X.U.FEFF.PERSNR,1,8))>19130101,]

#Byter variabelnamn och ändrar format på personnummer
Pso_behandling$PERSNR <- gsub("[^0-9]", "", Pso_behandling$PERSNR) 
#Pso_behandling <- merge(Pso_behandling,Pso_individ,all.x=TRUE, all.y=FALSE,by.x="PERSNR",by.y="PERSNR")

#Ändrar datatyper och tar bort behandlingar som sats in efter 2015-12-31
Pso_behandling$InsertDate <- as.Date(Pso_behandling$InsertDate)
Pso_behandling$RemoveDate <- as.Date(Pso_behandling$RemoveDate)
Pso_behandling <- subset(Pso_behandling, InsertDate<"2016-01-01")

#Pso_behandling <- with(Pso_behandling,data.frame(PatientID2,DrugName,InsertDate,RemoveDate,Region,Vårdnivå,Ålder,Sjukhus,ShortName,Department,PostalCode,PostOffice,ContactDate,ny_gamal_registrering))
#Pso_behandling$InsertDate <-substr(Pso_behandling$InsertDate, 1, 10)
#Pso_behandling$RemoveDate <-substr(Pso_behandling$RemoveDate, 1, 10)

#Lite småfix
Pso_behandling$DrugName <- as.character(Pso_behandling$DrugName)
Pso_behandling$DrugName[Pso_behandling$DrugName=="Metotrexat (injektion)"] <- "Metotrexat"
Pso_behandling$DrugName[Pso_behandling$DrugName=="Metotrexat (tablett)"] <- "Metotrexat"
Pso_behandling$DrugName[Pso_behandling$DrugName=="PUVA (tablett)"] <- "PUVA"
Pso_behandling$DrugName[Pso_behandling$DrugName=="PUVA (bad, TMP)"] <- "PUVA"
Pso_behandling$RemoveDate <- as.character(Pso_behandling$RemoveDate)


###Skapar dataset med endast Metotrexatbehandlingar
Pso_Metotrexat <- Pso_behandling[Pso_behandling$DrugName==c("Metotrexat"),]
## Sätter ett datum på Removedate på de behandlingar som inte än är utskrivna 
Pso_Metotrexat$RemoveDate[Pso_Metotrexat$RemoveDate==""] <- "2018-06-25"

##Skapar ett dataset med endast biologiska behandlingar
Pso_biologisk <- subset(Pso_behandling, biologisk="Ja")

##Skapar ett dataset med senaste biologisk behandling
Pso_bio <- Pso_biologisk[order(Pso_biologisk$InsertDate,decreasing=TRUE),]
Pso_bio <- Pso_bio[order(Pso_bio$PERSNR,decreasing=FALSE),]
Pso_bio$dupli_PatientID <- duplicated(Pso_bio$PERSNR)
Pso_bio<-subset(Pso_bio,dupli_PatientID==FALSE)

###

##Skapar dataset med andast aktiva systembehandlingar
Aktiva_behandlingar <-  subset(Pso_behandling,is.na(Pso_behandling$RemoveDate)=="TRUE")
Aktiva_behandlingar$DrugName <- as.factor(Aktiva_behandlingar$DrugName)


### Lägger till en variabel som anger om patienten är biologisk patient till dataramen ##Pso_individ

Pso_tmp1 <- subset(Aktiva_behandlingar, biologisk!="")
Pso_tmp1 <- Pso_tmp1[order(Pso_tmp1$biologisk),]
Pso_tmp1 <- Pso_tmp1[order(Pso_tmp1$PERSNR),]
Pso_tmp1$dupli <- duplicated(Pso_tmp1$PERSNR)
Pso_tmp1 <- subset(Pso_tmp1, dupli==FALSE)

mergdata <- data.frame(PERSNR=Pso_tmp1$PERSNR,aktiv_biologisk=Pso_tmp1$biologisk)

Pso_individ <- merge(Pso_individ, mergdata,all.x=TRUE, by.x="PERSNR", by.y="PERSNR")

```

```{r databearbetningar 3, echo=FALSE}
### plockar bort orimliga värden###

Pso_contact$Height[Pso_contact$Height>300] <- NA
Pso_contact$Height[Pso_contact$Height<100] <- NA

Pso_contact$Weight[Pso_contact$Weight>500] <- NA
Pso_contact$Weight[Pso_contact$Weight<20] <- NA

Pso_contact$Waist[Pso_contact$Waist>300] <- NA
Pso_contact$Waist[Pso_contact$Waist<20] <- NA

Pso_contact$BMI <- Pso_contact$Weight/(Pso_contact$Height/100)^2

```


```{r tabell_patientantal, echo=FALSE}

tab_patienter <- sort(table(Pso_individ$Sjukhus), decreasing=TRUE)

tab_patienter <- as.data.frame(tab_patienter)

kable(tab_patienter)
```



```{r stapel_systembehandlingar, echo=FALSE, fig.width=18, fig.height=15}
#names(df) <- c("RemoveDate", "Treatment", "Hospcode", "Sjukhuskod", "Sjukhusnamn", "sjukhusnamn_miljo","Regbehor")



#plot1 <- table(Aktiva_behandlingar[,2])
#plot1 <-  rbind(table(Aktiva_behandlingar$Treatment)/sum(table(Aktiva_behandlingar$Treatment))*100, 
#table(klin_aktiva_behandlingar$Treatment)/sum(table(klin_aktiva_behandlingar$Treatment))*100)

plot1 <- table(Aktiva_behandlingar$DrugName)/sum(table(Aktiva_behandlingar$DrugName))*100

antal <- paste(table(Aktiva_behandlingar$DrugName),"\n(",round(as.numeric(plot1)),"%",")",sep="")
par(mar=c(11.1, 4.1 , 4.1 , 1.1),cex=1.9)
bar1 <- barplot(plot1,ylab="Andel pågående Systembehandlingar (%)",las=2,col=c("cadetblue"),ylim=c(0,max(plot1)*1.2),space=c(0,0.5))

text(bar1, plot1, antal,cex=0.8,pos=3)


#legend("topright","groups",ncol=1,c("Riket",print(klin_aktiva_behandlingar$sjukhusnamn_miljo[1])),
 #      fill=c("cadetblue","goldenrod3"),cex=1)

```



```{r stapel_kombinationsbehandlingar, echo=FALSE, eval=TRUE,fig.width=7, fig.height=9}

sys <- Aktiva_behandlingar
sys$DrugName <- as.character(sys$DrugName)
sys$PERSNR <- factor(sys$PERSNR)
sys <- subset(sys, is.na(DrugName)==FALSE)
sys$indikator <-  rep(1,nrow(sys))



mean2 <- function(x){
        mean(x,na.rm=TRUE)
}


sys2 <- cast(sys, PERSNR ~ DrugName,value="indikator", fun.aggregate=mean2)

sys2 <- as.data.frame(sys2)

sys3 <- unstack(within(stack(sys2), values[is.nan(values)] <- 0))

sys3$PNR <- sys2$PERSNR



ant <- ncol(sys3)-1
sys3$antal_läkemedel <- rowSums(sys3[,1:ant])


sys3$Acitretin..Neotigason. <- as.character(sys3$Acitretin..Neotigason.)
sys3$Acitretin..Neotigason.[sys3$Acitretin..Neotigason.=="1"] <- "Acitretin"

sys3$Adalimumab..Humira. <- as.character(sys3$Adalimumab..Humira.)
sys3$Adalimumab..Humira.[sys3$Adalimumab..Humira.=="1"] <- "Adalimumab"

sys3$Acitretin..Neotigason. <- as.character(sys3$Acitretin..Neotigason.)
sys3$Acitretin..Neotigason.[sys3$Acitretin..Neotigason.=="1"] <- "Acitretin (Neotigason)"

sys3$Alitretinoin..Toctino. <- as.character(sys3$Alitretinoin..Toctino.)
sys3$Alitretinoin..Toctino.[sys3$Alitretinoin..Toctino.=="1"] <- "Alitretinoin"

sys3$Ciklosporin..Sandimmum. <- as.character(sys3$Ciklosporin..Sandimmum.)
sys3$Ciklosporin..Sandimmum.[sys3$Ciklosporin..Sandimmum.=="1"] <- "Ciklosporin"

sys3$Efalizumab..Raptiva. <- as.character(sys3$Efalizumab..Raptiva.)
sys3$Efalizumab..Raptiva.[sys3$Efalizumab..Raptiva.=="1"] <- "Efalizumab"

sys3$Etanercept..Enbrel. <- as.character(sys3$Etanercept..Enbrel.)
sys3$Etanercept..Enbrel.[sys3$Etanercept..Enbrel.=="1"] <- "Etanercept"

sys3$Fumaderm..Fumarsyra. <- as.character(sys3$Fumaderm..Fumarsyra.)
sys3$Fumaderm..Fumarsyra.[sys3$Fumaderm..Fumarsyra.=="1"] <- "Fumaderm"

sys3$Infliximab..Remicade. <- as.character(sys3$Infliximab..Remicade.)
sys3$Infliximab..Remicade.[sys3$Infliximab..Remicade.=="1"] <- "Infliximab"

sys3$Metotrexat <- as.character(sys3$Metotrexat)
sys3$Metotrexat[sys3$Metotrexat=="1"] <- "Metotrexat"

sys3$PUVA <- as.character(sys3$PUVA)
sys3$PUVA[sys3$PUVA=="1"] <- "PUVA"

sys3$Tioguanin..Lanvis. <- as.character(sys3$Tioguanin..Lanvis.)
sys3$Tioguanin..Lanvis.[sys3$Tioguanin..Lanvis.=="1"] <- "Tioguanin"

sys3$Ustekinumab..Stelara. <- as.character(sys3$Ustekinumab..Stelara.)
sys3$Ustekinumab..Stelara.[sys3$Ustekinumab..Stelara.=="1"] <- "Ustekinumab"

if("Apremilast..Otezla." %in% names(sys3)){
        sys3$Apremilast..Otezla. <- as.character(sys3$Apremilast..Otezla.)
        sys3$Apremilast..Otezla.[sys3$Apremilast..Otezla.=="1"] <- "Aprimelast"
}

if("Infliximab.Biosimilar..Inflectra.Remsima." %in% names(sys3)){
        sys3$Infliximab.Biosimilar..Inflectra.Remsima. <- as.character(sys3$Infliximab.Biosimilar..Inflectra.Remsima.)
        sys3$Infliximab.Biosimilar..Inflectra.Remsima.[sys3$Infliximab.Biosimilar..Inflectra.Remsima.=="1"] <- "Infliximab.Bio"
        
}

if("Sekukinumab..Cosentyx." %in% names(sys3)){
        sys3$Sekukinumab..Cosentyx. <- as.character(sys3$Sekukinumab..Cosentyx.)
        sys3$Sekukinumab..Cosentyx.[sys3$Sekukinumab..Cosentyx.=="1"] <- "Sekukinumab"
        
}


sys3[sys3=="0"] <- ""


kombi <-  paste(sys3[,1],sys3[,2],sys3[,3],sys3[,4],sys3[,5],sys3[,6],sys3[,7],sys3[,8],sys3[,9],sys3[,10],sys3[,11],sys3[,12])



if(ncol(sys3)>14)
        kombi <- paste(kombi, sys3[,13])

if(ncol(sys3)>15)
        kombi <- paste(kombi, sys3[,14])

if(ncol(sys3)>16)
        kombi <- paste(kombi, sys3[,15])

if(ncol(sys3)>17)
        kombi <- paste(kombi, sys3[,16])

if(ncol(sys3)>18)
        kombi <- paste(kombi, sys3[,17])


sys3$kombi_läkemedel <- str_replace_all(string=kombi, pattern=" ", repl="")

sys3 <- subset(sys3,antal_läkemedel>1)

#sta <- stat.table(index=list(kombi_läkemedel), contents=count(), data=sys3, margins=1)

sys <- sys[order(sys$InsertDate,decreasing=TRUE),]

sys$dupli <- duplicated(sys$PERSNR)

dat_sjuk <- subset(sys, dupli==FALSE)

dat_sjuk <- dat_sjuk[,1:3]

dat_sjuk <- dat_sjuk[,-2]

dats <- merge(sys3,dat_sjuk,by.x="PNR",by.y="PERSNR")

dats$kombi_läkemedel[dats$kombi_läkemedel=="AdalimumabMetotrexat"] <- "Adalimumab:Metotrexat"

dats$kombi_läkemedel[dats$kombi_läkemedel=="AdalimumabEtanercept"] <- "Adalimumab:Etanercept"
dats$kombi_läkemedel[dats$kombi_läkemedel=="EtanerceptMetotrexat"] <- "Etanercept:Metotrexat"
dats$kombi_läkemedel[dats$kombi_läkemedel=="InfliximabMetotrexat"] <- "Infliximab:Metotrexat"
dats$kombi_läkemedel[dats$kombi_läkemedel=="Metotrexat1"] <- "Ustekinumab:Metotrexat"
dats$kombi_läkemedel[dats$kombi_läkemedel=="AcitretinMetotrexat"] <- "Acitretin:Metotrexat"
dats$kombi_läkemedel[dats$kombi_läkemedel=="CiklosporinMetotrexat"] <- "Ciklosporin:Metotrexat"
dats$kombi_läkemedel[dats$kombi_läkemedel=="AcitretinEtanercept"] <- "Acitretin:Etanercept"
dats$kombi_läkemedel[dats$kombi_läkemedel=="Acitretin1"] <- "Acitretin:Ustekinumab"
dats$kombi_läkemedel[dats$kombi_läkemedel=="AcitretinAdalimumab"] <- "Acitretin:Adalimumab"
dats$kombi_läkemedel[dats$kombi_läkemedel=="AcitretinPUVA"] <- "Acitretin:PUVA"
dats$kombi_läkemedel[dats$kombi_läkemedel=="Infliximab1"] <- "Infliximab:Ustekinumab"
dats$kombi_läkemedel[dats$kombi_läkemedel=="MetotrexatPUVA"] <-  "PUVA:Metotrexat"
dats$kombi_läkemedel[dats$kombi_läkemedel=="AcitretinAlitretinoin"] <- "Acitretin:Alitretinoin"
dats$kombi_läkemedel[dats$kombi_läkemedel=="AcitretinCiklosporin"] <- "Acitretin:Ciklosporin"
dats$kombi_läkemedel[dats$kombi_läkemedel=="AcitretinEfalizumab"] <- "Acitretin:Efalizumab"
dats$kombi_läkemedel[dats$kombi_läkemedel=="AcitretinMetotrexat1"] <- "Acitretin:Metotrexat:Ustekinumab"
dats$kombi_läkemedel[dats$kombi_läkemedel=="Adalimumab1"] <- "Adalimumab:Ustekinumab"
dats$kombi_läkemedel[dats$kombi_läkemedel=="AdalimumabEtanercept1"] <- "Adalimumab:Etanercept:Metotrexat"
dats$kombi_läkemedel[dats$kombi_läkemedel=="AdalimumabInfliximabMetotrexat"] <- "Adalimumab:Infliximab:Metotrexat"
dats$kombi_läkemedel[dats$kombi_läkemedel=="AdalimumabPUVA"] <- "Adalimumab:PUVA"
dats$kombi_läkemedel[dats$kombi_läkemedel=="CiklosporinEtanercept"] <- "Ciklosporin:Etanercept"


dats$kombi_läkemedel[dats$kombi_läkemedel=="Etanercept1"] <- "Etanercept:Ustekinumab"
dats$kombi_läkemedel[dats$kombi_läkemedel=="EtanerceptMetotrexat1"] <- "EtanerceptMetotrexat:Ustekinumab"
dats$kombi_läkemedel[dats$kombi_läkemedel=="Fumaderm1"] <- "Fumaderm:Ustekinumab"
dats$kombi_läkemedel[dats$kombi_läkemedel=="InfliximabMetotrexat1"] <- "InfliximabMetotrexat:Ustekinumab"

dats$kombi_läkemedel[dats$kombi_läkemedel=="MetotrexatUstekinumab"] <- "Metotrexat:Ustekinumab"
dats$kombi_läkemedel[dats$kombi_läkemedel=="AcitretinUstekinumab"] <- "Acitretin:Ustekinumab"
#######
tabl <- table(dats$kombi_läkemedel)



tabl <- as.table(tabl[order(tabl,decreasing=TRUE)][1:10])
tabl <- tabl[order(tabl,decreasing=FALSE)]

par(mar=c(3,15,2,2))
bar1 <- barplot(tabl,las=2,horiz=TRUE,col="cadetblue",main="Kombinationsbehandingar",xaxt="n",xlim=c(0,max(tabl)+25),cex.main=0.9)
axis(side=1)
text(tabl,bar1,tabl,cex=0.8,pos=4)
```



```{r linjegraf_systembehandlingar, echo=FALSE}

Pso_beh_2011 <- subset(Pso_behandling, InsertDate< "2012-01-01")
Pso_beh_2011 <- subset(Pso_beh_2011, RemoveDate> "2011-12-31"|is.na(RemoveDate)==TRUE)
Pso_beh_2011$År_behandling <- rep(2011, nrow(Pso_beh_2011))

Pso_beh_2012 <- subset(Pso_behandling, InsertDate< "2013-01-01")
Pso_beh_2012 <- subset(Pso_beh_2012, RemoveDate> "2012-12-31"|is.na(RemoveDate)==TRUE)
Pso_beh_2012$År_behandling <- rep(2012, nrow(Pso_beh_2012))

Pso_beh_2013 <- subset(Pso_behandling, InsertDate< "2014-01-01")
Pso_beh_2013 <- subset(Pso_beh_2013, RemoveDate> "2013-12-31"|is.na(RemoveDate)==TRUE)
Pso_beh_2013$År_behandling <- rep(2013, nrow(Pso_beh_2013))

Pso_beh_2014 <- subset(Pso_behandling, InsertDate< "2015-01-01")
Pso_beh_2014 <- subset(Pso_beh_2014, RemoveDate> "2014-12-31"|is.na(RemoveDate)==TRUE)
Pso_beh_2014$År_behandling <- rep(2014, nrow(Pso_beh_2014))

Pso_beh_2015 <- subset(Pso_behandling, InsertDate< "2016-01-01")
Pso_beh_2015 <- subset(Pso_beh_2015, RemoveDate> "2015-12-31"|is.na(RemoveDate)==TRUE)
Pso_beh_2015$År_behandling <- rep(2015, nrow(Pso_beh_2015))


Pso_linjegrafdata <- rbind(Pso_beh_2011, Pso_beh_2012, Pso_beh_2013, Pso_beh_2014, Pso_beh_2015)


#linjegrafdata_bio <- subset(Pso_linjegrafdata, biologisk=="Ja")
#Pso_linjegrafdata <- subset(Pso_linjegrafdata, biologisk=="Ja")

data_plot <-  Pso_linjegrafdata %>% group_by(År_behandling, DrugName) %>% 
        summarise(antal = n()) %>% 
        group_by(year = År_behandling) %>% 
        mutate(ntot = sum(antal), p = antal/ntot)

data_plot <- as.data.frame(data_plot)

tabel_behand<- cast(data_plot, DrugName ~ År_behandling  ,value="p")
tabel_behand <- as.data.frame(tabel_behand) 
tabel_behand[,2:ncol(tabel_behand)] <- round(tabel_behand[,2:ncol(tabel_behand)]*100 ,2)

tabel_behand[is.na(tabel_behand)] <- 0

kable(tabel_behand)
#ggplot(data=data_plot ,aes(x = År_behandling, y = p, color = DrugName))  + theme_minimal() + #geom_line(lwd = 1)


```


```{r befolkningspyramid,fig.width=9,fig.height=7 ,echo=FALSE}

tabsa <- table(Pso_individ$Kön, Pso_individ$Ålder_kategori2)

dat1 <-as.numeric(tabsa[1,])
dat2 <- as.numeric(tabsa[2,])
names(dat1) <- c('10-14','15-19','20-24','25-29','30-34','35-39','40-44','45-49','50-54','55-59','60-64','65-69','70-74','75-79','80-84','85-89','90-94')
names(dat2) <- names(dat1)

dat_pyr <- data.frame(dat1, dat2)

#par(mar=c(3, 3.1 , 2 , 3.1))
pyramid(dat_pyr,Llab="Kvinnor",Rlab="Män",Rcol="blue", Lcol="red",Clab="Ålder",Laxis=c(0,50,100,150,200,250,300,350),Csize=1.3)

```


