---
title: "PsoReg årsrapport 2016"
author: "Simon Lokal"
date: '`r Sys.Date()`'
output: html_document
---

```{r librarys, warning=FALSE, message = FALSE}
library(knitr)
library(stringr)
library(GynopTools)
```

```{r databearbetningar1, echo=FALSE, cache=TRUE}
#setwd("H:/Martin/PsoReg/Projekt PsoReg årsrapport 2016/årsrapport 2016 WD/Pso årsrapport 2016/Pso-16")
# setwd("C:/WD/PsoReg/PsoReg/")


#library(data.table)

#Läser in data med kontakter från PsoReg
Pso_contact <- read.delim("../PsoReg/Kontaktnivå 20160118.txt",header=TRUE,sep="\t",encoding="UTF-8", dec=",")

#namnger variablerna ändra datatyper, plockar bort testpatienter och plockar bort kontakter utan kontaktdatum och kontakter efter 2015-12-31
names(Pso_contact)[1:9]<- c("PERSNR","Pnyckel_contact","Pnyckel_root","Fnyckel_contact","PAT_ID","Kön","Aktiv_patient", "Sjukhus","ContactDate")
Pso_contact$Sjukhus <- as.character(Pso_contact$Sjukhus)
Pso_contact <- Pso_contact[!(Pso_contact$Sjukhus=="Test") ,]
Pso_contact$ContactDate <- as.Date(Pso_contact$ContactDate)
Pso_contact <- subset(Pso_contact, is.na(ContactDate)==FALSE)
Pso_contact <- subset(Pso_contact, ContactDate<"2016-01-01")


#Sorterar datat och skapar en variabel som indikerar de unika individerna dupli_PatientID=FALSE=första kontakten per individ
Pso_contact <- Pso_contact[order(Pso_contact$ContactDate,decreasing=FALSE),]
Pso_contact <- Pso_contact[order(Pso_contact$PERSNR,decreasing=FALSE),]
Pso_contact$dupli_PatientID <- duplicated(Pso_contact$PERSNR)

#lite fix
Pso_contact$Contact_year <- 1900 + as.POSIXlt(Pso_contact$ContactDate)$year
Pso_contact$Contact_moth <-1 + as.POSIXlt(Pso_contact$ContactDate)$mon
Pso_contact$Contact_year_moth <- paste(as.character(Pso_contact$Contact_year),as.character(Pso_contact$Contact_moth),sep ="")
Pso_contact$REGDATUM <- as.character(Pso_contact$REGDATUM)
Pso_contact$REGDATUM[Pso_contact$REGDATUM==""] <- "1900-01-01"
Pso_contact$REGDATUM <- as.Date(Pso_contact$REGDATUM)
Pso_contact$Registred_year <- 1900 + as.POSIXlt(Pso_contact$REGDATUM)$year
Pso_contact$Registred_moth <-1 + as.POSIXlt(Pso_contact$REGDATUM)$mon
Pso_contact$Registred_year_moth <- paste(as.character(Pso_contact$Registred_year),as.character(Pso_contact$Registred_moth),sep ="")

#Skapar dataset med den senaste kontakten per individ
Pso_individ<-subset(Pso_contact,dupli_PatientID==FALSE)
###############



```


```{r databearbetningar2, echo=FALSE, cache=TRUE}
#####Läser in fil med systembehandlingar#####

#Läser in data med PsoReg data för att skapa dataset med behandlingar
Pso_behandling <- read.csv("../PsoReg/Systembehandlingar 20160118.txt",header=TRUE,sep="\t",encoding="UTF-8")
names(Pso_behandling) <- c("PERSNR", "Pnyckel_systemictreat", "Fnyckel_systemictreat","Sjukhus", "InsertDate", "RemoveDate", "DrugName","biologisk","Aktiv_patient")
Pso_behandling <- Pso_behandling[!(Pso_behandling$Sjukhus=="Test") ,]
#Pso_behandling <- Pso_behandling[as.numeric(substr(Pso_behandling$X.U.FEFF.PERSNR,1,8))>19130101,]

#Byter variabelnamn och ändrar format på personnummer
Pso_behandling$PERSNR <- gsub("[^0-9]", "", Pso_behandling$PERSNR) 
#Pso_behandling <- merge(Pso_behandling,Pso_individ,all.x=TRUE, all.y=FALSE,by.x="PERSNR",by.y="PERSNR")

#Ändrar datatyper och tar bort behandlingar som sats in efter 2015-12-31
Pso_behandling$InsertDate <- as.Date(Pso_behandling$InsertDate)
Pso_behandling$RemoveDate <- as.Date(Pso_behandling$RemoveDate)
Pso_behandling <- subset(Pso_behandling, InsertDate<"2016-01-01")

#Pso_behandling <- with(Pso_behandling,data.frame(PatientID2,DrugName,InsertDate,RemoveDate,Region,Vårdnivå,Ålder,Sjukhus,ShortName,Department,PostalCode,PostOffice,ContactDate,ny_gamal_registrering))
#Pso_behandling$InsertDate <-substr(Pso_behandling$InsertDate, 1, 10)
#Pso_behandling$RemoveDate <-substr(Pso_behandling$RemoveDate, 1, 10)

#Lite småfix
Pso_behandling$DrugName <- as.character(Pso_behandling$DrugName)
Pso_behandling$DrugName[Pso_behandling$DrugName=="Metotrexat (injektion)"] <- "Metotrexat"
Pso_behandling$DrugName[Pso_behandling$DrugName=="Metotrexat (tablett)"] <- "Metotrexat"
Pso_behandling$DrugName[Pso_behandling$DrugName=="PUVA (tablett)"] <- "PUVA"
Pso_behandling$RemoveDate <- as.character(Pso_behandling$RemoveDate)


###Skapar dataset med endast Metotrexatbehandlingar
Pso_mtx <- Pso_behandling[Pso_behandling$DrugName==c("Metotrexat"),]
## Sätter ett datum på Removedate på de behandlingar som inte än är utskrivna 
Pso_mtx$RemoveDate[Pso_mtx$RemoveDate==""] <- "2018-06-25"

##Skapar ett dataset med endast biologiska behandlingar
Pso_biologisk <- subset(Pso_behandling, biologisk="Ja")

##Skapar ett dataset med senaste biologisk behandling
Pso_bio <- Pso_biologisk[order(Pso_biologisk$InsertDate,decreasing=TRUE),]
Pso_bio <- Pso_bio[order(Pso_bio$PERSNR,decreasing=FALSE),]
Pso_bio$dupli_PatientID <- duplicated(Pso_bio$PERSNR)
Pso_bio<-subset(Pso_bio,dupli_PatientID==FALSE)

```

```{r databearbetningar 3, echo=FALSE, cache=TRUE, dependson='databearbetningar1'}
### plockar bort orimliga värden###

Pso_contact$Height[Pso_contact$Height>300] <- NA
Pso_contact$Height[Pso_contact$Height<100] <- NA

Pso_contact$Weight[Pso_contact$Weight>500] <- NA
Pso_contact$Weight[Pso_contact$Weight<20] <- NA

Pso_contact$Waist[Pso_contact$Waist>300] <- NA
Pso_contact$Waist[Pso_contact$Waist<20] <- NA

Pso_contact$BMI <- Pso_contact$Weight/(Pso_contact$Height/100)^2

```


```{r tabell_patientantal, echo=FALSE}

tab_patienter <- sort(table(Pso_individ$Sjukhus), decreasing=TRUE)

tab_patienter <- as.data.frame(tab_patienter)

kable(tab_patienter)
```

```{r antal_pat_arsrapport, echo=FALSE}

Sort= Pso_contact[with(Pso_contact, order(as.Date(Pso_contact$ContactDate), Pso_contact$PERSNR)), ]  #sorterar patient enligt reg.datum och  
Sort$unikaPNR <- duplicated(Sort$PERSNR)
Sort=subset(Sort,Sort$unikaPNR==FALSE)
ar=format(as.Date(Sort$ContactDate), "%Y")
Sort$ar=ar
Sort=Sort[-c(1,2),]

artab <- Sort %>% group_by(ar) %>% summarise(n = n())

par(mfcol=c(1,1))

plot(artab$ar, cumsum(artab$n), type = 'l',xlab="År",ylab="Antal registrerade patienter",lty=c(1,1),lwd=c(3,3),col="dodgerblue2",xlim=c(2005.8,as.integer(max(artab$ar))+0.3),ylim=c(0,sum(artab$n)*1.05),yaxs="i",xaxs="i",xaxt="n")

axis(1, at = seq(2006, as.integer(max(artab$ar)), by = 1), las=2)

lines(x=c(as.integer(min(artab$ar))+0.3,as.integer(max(artab$ar))+0.3),y=c(1000,1000),lty = 2, col ="gray") 
lines(x=c(as.integer(min(artab$ar))+0.3,as.integer(max(artab$ar))+0.3),y=c(2000,2000),lty = 2, col ="gray")
lines(x=c(as.integer(min(artab$ar))+0.3,as.integer(max(artab$ar))+0.3),y=c(3000,3000),lty = 2, col ="gray")
lines(x=c(as.integer(min(artab$ar))+0.3,as.integer(max(artab$ar))+0.3),y=c(4000,4000),lty = 2, col ="gray")
lines(x=c(as.integer(min(artab$ar))+0.3,as.integer(max(artab$ar))+0.3),y=c(5000,5000),lty = 2, col ="gray")

# lägger in punkter och akumulerat antal patienter för varje år
for (i in 2:length(artab$ar)
) {                                             
  points(2005+i,sum(as.vector(artab[1:i,2])),pch = 20,col="firebrick1")
  text(2005+i-0.13,sum(as.vector(artab[1:i,2]))+180,sum(as.vector(artab[1:i,2])))
  }
points(2006,sum(as.vector(artab[1:1,2])),pch = 20,col="firebrick1")
  text(2006+0.03,sum(as.vector(artab[1:1,2]))+180,sum(as.vector(artab[1:1,2])))
```

```{r utfallsM_arsrapport, echo=FALSE}

PASI=Pso_contact


```

head(Pso_contact)
